import os

GROUP = "locust.io"
VERSION = "v1"
API_VERSION = GROUP + "/" + VERSION

KIND = "LocustTest"
PLURAL = "locusttests"
LOCUST_TEST_RESOURCE = f"{PLURAL}.{VERSION}.{GROUP}"

LABEL_ANNOTATION_PREFIX = f"{GROUP}"

IN_CLUSTER = os.getenv("KUBERNETES_SERVICE_HOST")
